try veya catch bloklarının ardından gelen finally bloğu, try-catch bloğu tamamlandığında her durumda çalışır.
Bu örnekte, finally bloğunda sadece basit bir mesaj ("Try-catch bloğu tamamlandı.") yazdırıyoruz.
Bu mesaj her döngü çalıştırıldığında, hata olup olmadığına bakılmaksızın ekrana yazdırılacaktır.
